export type CALevel = 'FOUNDATION' | 'INTERMEDIATE' | 'FINAL';

export interface ExamAttemptConfig {
  id: string;
  caLevel: CALevel;
  attemptLabel: string;
  attemptCode: string;
  examMonth: string;
  examYear: number;
  sequenceOrder: number;
  active: boolean;
  syllabusVersion: string;
  applicableMaterialVersion?: string;
}

/**
 * Single source of truth for ICAI CA Exam Attempts.
 * Foundation: May 2024 to September 2027 (Jan, May, Sep pattern. NO November).
 * Intermediate: May 2024 to September 2027 (Jan, May, Sep pattern. NO November).
 * Final:
 *   - May 2024 to January 2026: 3-attempt pattern.
 *   - From 2026 onward: NO September 2026. After May 2026, ONLY Nov 2026, May 2027, Nov 2027.
 *   - NO January 2027, NO September 2027.
 */
export const ATTEMPT_MASTER_CONFIG: ExamAttemptConfig[] = [
  // =========================================================================
  // CA FOUNDATION ATTEMPTS (11 attempts)
  // =========================================================================
  {
    id: 'att_fnd_may24',
    caLevel: 'FOUNDATION',
    attemptLabel: 'May 2024',
    attemptCode: 'FND_MAY24',
    examMonth: 'May',
    examYear: 2024,
    sequenceOrder: 1,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_sep24',
    caLevel: 'FOUNDATION',
    attemptLabel: 'September 2024',
    attemptCode: 'FND_SEP24',
    examMonth: 'September',
    examYear: 2024,
    sequenceOrder: 2,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_jan25',
    caLevel: 'FOUNDATION',
    attemptLabel: 'January 2025',
    attemptCode: 'FND_JAN25',
    examMonth: 'January',
    examYear: 2025,
    sequenceOrder: 3,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_may25',
    caLevel: 'FOUNDATION',
    attemptLabel: 'May 2025',
    attemptCode: 'FND_MAY25',
    examMonth: 'May',
    examYear: 2025,
    sequenceOrder: 4,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_sep25',
    caLevel: 'FOUNDATION',
    attemptLabel: 'September 2025',
    attemptCode: 'FND_SEP25',
    examMonth: 'September',
    examYear: 2025,
    sequenceOrder: 5,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_jan26',
    caLevel: 'FOUNDATION',
    attemptLabel: 'January 2026',
    attemptCode: 'FND_JAN26',
    examMonth: 'January',
    examYear: 2026,
    sequenceOrder: 6,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_may26',
    caLevel: 'FOUNDATION',
    attemptLabel: 'May 2026',
    attemptCode: 'FND_MAY26',
    examMonth: 'May',
    examYear: 2026,
    sequenceOrder: 7,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_sep26',
    caLevel: 'FOUNDATION',
    attemptLabel: 'September 2026',
    attemptCode: 'FND_SEP26',
    examMonth: 'September',
    examYear: 2026,
    sequenceOrder: 8,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_jan27',
    caLevel: 'FOUNDATION',
    attemptLabel: 'January 2027',
    attemptCode: 'FND_JAN27',
    examMonth: 'January',
    examYear: 2027,
    sequenceOrder: 9,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_may27',
    caLevel: 'FOUNDATION',
    attemptLabel: 'May 2027',
    attemptCode: 'FND_MAY27',
    examMonth: 'May',
    examYear: 2027,
    sequenceOrder: 10,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fnd_sep27',
    caLevel: 'FOUNDATION',
    attemptLabel: 'September 2027',
    attemptCode: 'FND_SEP27',
    examMonth: 'September',
    examYear: 2027,
    sequenceOrder: 11,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },

  // =========================================================================
  // CA INTERMEDIATE ATTEMPTS (11 attempts)
  // =========================================================================
  {
    id: 'att_int_may24',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'May 2024',
    attemptCode: 'INT_MAY24',
    examMonth: 'May',
    examYear: 2024,
    sequenceOrder: 1,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_sep24',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'September 2024',
    attemptCode: 'INT_SEP24',
    examMonth: 'September',
    examYear: 2024,
    sequenceOrder: 2,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_jan25',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'January 2025',
    attemptCode: 'INT_JAN25',
    examMonth: 'January',
    examYear: 2025,
    sequenceOrder: 3,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_may25',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'May 2025',
    attemptCode: 'INT_MAY25',
    examMonth: 'May',
    examYear: 2025,
    sequenceOrder: 4,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_sep25',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'September 2025',
    attemptCode: 'INT_SEP25',
    examMonth: 'September',
    examYear: 2025,
    sequenceOrder: 5,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_jan26',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'January 2026',
    attemptCode: 'INT_JAN26',
    examMonth: 'January',
    examYear: 2026,
    sequenceOrder: 6,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_may26',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'May 2026',
    attemptCode: 'INT_MAY26',
    examMonth: 'May',
    examYear: 2026,
    sequenceOrder: 7,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_sep26',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'September 2026',
    attemptCode: 'INT_SEP26',
    examMonth: 'September',
    examYear: 2026,
    sequenceOrder: 8,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_jan27',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'January 2027',
    attemptCode: 'INT_JAN27',
    examMonth: 'January',
    examYear: 2027,
    sequenceOrder: 9,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_may27',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'May 2027',
    attemptCode: 'INT_MAY27',
    examMonth: 'May',
    examYear: 2027,
    sequenceOrder: 10,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_int_sep27',
    caLevel: 'INTERMEDIATE',
    attemptLabel: 'September 2027',
    attemptCode: 'INT_SEP27',
    examMonth: 'September',
    examYear: 2027,
    sequenceOrder: 11,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },

  // =========================================================================
  // CA FINAL ATTEMPTS (10 attempts)
  // =========================================================================
  {
    id: 'att_fin_may24',
    caLevel: 'FINAL',
    attemptLabel: 'May 2024',
    attemptCode: 'FIN_MAY24',
    examMonth: 'May',
    examYear: 2024,
    sequenceOrder: 1,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_sep24',
    caLevel: 'FINAL',
    attemptLabel: 'September 2024',
    attemptCode: 'FIN_SEP24',
    examMonth: 'September',
    examYear: 2024,
    sequenceOrder: 2,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_jan25',
    caLevel: 'FINAL',
    attemptLabel: 'January 2025',
    attemptCode: 'FIN_JAN25',
    examMonth: 'January',
    examYear: 2025,
    sequenceOrder: 3,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_may25',
    caLevel: 'FINAL',
    attemptLabel: 'May 2025',
    attemptCode: 'FIN_MAY25',
    examMonth: 'May',
    examYear: 2025,
    sequenceOrder: 4,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_sep25',
    caLevel: 'FINAL',
    attemptLabel: 'September 2025',
    attemptCode: 'FIN_SEP25',
    examMonth: 'September',
    examYear: 2025,
    sequenceOrder: 5,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_jan26',
    caLevel: 'FINAL',
    attemptLabel: 'January 2026',
    attemptCode: 'FIN_JAN26',
    examMonth: 'January',
    examYear: 2026,
    sequenceOrder: 6,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_may26',
    caLevel: 'FINAL',
    attemptLabel: 'May 2026',
    attemptCode: 'FIN_MAY26',
    examMonth: 'May',
    examYear: 2026,
    sequenceOrder: 7,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_nov26',
    caLevel: 'FINAL',
    attemptLabel: 'November 2026',
    attemptCode: 'FIN_NOV26',
    examMonth: 'November',
    examYear: 2026,
    sequenceOrder: 8,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_may27',
    caLevel: 'FINAL',
    attemptLabel: 'May 2027',
    attemptCode: 'FIN_MAY27',
    examMonth: 'May',
    examYear: 2027,
    sequenceOrder: 9,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
  {
    id: 'att_fin_nov27',
    caLevel: 'FINAL',
    attemptLabel: 'November 2027',
    attemptCode: 'FIN_NOV27',
    examMonth: 'November',
    examYear: 2027,
    sequenceOrder: 10,
    active: true,
    syllabusVersion: 'New Scheme 2024',
  },
];
