import React from 'react';
import { ShieldCheck, Scale, FileText, AlertCircle } from 'lucide-react';

export const LegalPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 text-slate-100 space-y-12">
      {/* Title */}
      <div className="space-y-3">
        <h1 className="text-3xl font-extrabold text-white">Terms, Policies & Legal Compliance</h1>
        <p className="text-xs text-slate-400">Last updated: May 2026</p>
      </div>

      {/* ICAI Disclaimer */}
      <div className="p-6 rounded-2xl bg-amber-500/10 border border-amber-500/30 space-y-2 text-xs">
        <h3 className="font-bold text-amber-300 flex items-center gap-2">
          <Scale className="w-4 h-4" />
          ICAI Official Disclaimer & Non-Affiliation Notice
        </h3>
        <p className="text-slate-300 leading-relaxed">
          &ldquo;Chartered Accountant&rdquo;, &ldquo;CA&rdquo;, and &ldquo;ICAI&rdquo; are registered trademarks of The Institute of Chartered Accountants of India (ICAI).
          CA Exam Checker AI is an independent academic software technology built for educational preparation and self-assessment purposes only.
          This platform is not affiliated with, endorsed by, or operated under the authority of the Institute of Chartered Accountants of India.
          Evaluations generated by this tool are indicative study aids and do not constitute official examination scores.
        </p>
      </div>

      {/* Terms of Service */}
      <div className="space-y-4 text-xs text-slate-300 leading-relaxed">
        <h2 className="text-lg font-bold text-white">1. Terms of Service</h2>
        <p>
          By creating an account or accessing CA Exam Checker AI, you agree to abide by these terms. Our service evaluates candidate answer sheets
          against publicly accessible suggested answers, statutory standards, and test series rubrics. You agree not to upload harmful, offensive,
          or non-educational materials to the system.
        </p>
      </div>

      {/* Privacy Policy */}
      <div className="space-y-4 text-xs text-slate-300 leading-relaxed">
        <h2 className="text-lg font-bold text-white">2. Privacy Policy & Document Protection</h2>
        <p>
          We treat candidate answer sheets and personal details with strict academic confidentiality. Your uploaded papers are processed securely
          in transient memory for the sole purpose of generating your evaluation report. We do not sell or monetize candidate data.
          Candidate names and ICAI registration numbers are stored exclusively to render your personal scorecards and prevent duplicate free-tier claims.
        </p>
      </div>

      {/* Refund & Cancellation Policy */}
      <div className="space-y-4 text-xs text-slate-300 leading-relaxed">
        <h2 className="text-lg font-bold text-white">3. Refund & Cancellation Policy</h2>
        <p>
          We are committed to fair and transparent billing for all CA aspirants:
        </p>
        <ul className="list-disc list-inside space-y-2 text-slate-300">
          <li>
            <strong>Safeguard Protection:</strong> If an uploaded file fails the document authenticity check (e.g. an admit card or blank image is uploaded),
            the system rejects the file and <strong>zero evaluation credits are deducted</strong>.
          </li>
          <li>
            <strong>Unconsumed Credits:</strong> Candidates may request a refund for unconsumed, purchased credit packages within 7 days of payment
            by emailing <a href="mailto:caexamchecker.support@gmail.com" className="text-amber-400 underline">caexamchecker.support@gmail.com</a>.
          </li>
          <li>
            <strong>Completed Evaluations:</strong> Due to server and AI computation costs, credits utilized for completed evaluations are non-refundable.
          </li>
        </ul>
      </div>

      {/* Contact for Grievances */}
      <div className="pt-6 border-t border-slate-800 text-xs text-slate-400 space-y-1">
        <p>
          Grievance Officer & Legal Helpdesk:{' '}
          <a href="mailto:caexamchecker.support@gmail.com" className="text-amber-400 hover:underline">
            caexamchecker.support@gmail.com
          </a>
        </p>
      </div>
    </div>
  );
};
